name: CI
on:
  push:
    branches: 
      - master

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          persist-credentials: false
          
      - name: Install and Build
        run: |
          npm i  
          npm  run docs:build
      - name: Deploy  
        run: |
          cd ./src/.vuepress/dist/
          echo 12tall.cn > CNAME  
          git config --global user.name "${GITHUB_ACTOR}"
          git init
          git add -A
          git commit -m "Auto Deploy"
          git push -f "https://${GITHUB_ACTOR}:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" HEAD:gh-pages
